apiVersion: apps/v1
kind: Deployment
metadata:
  name: distance-conversion
spec:
  replicas: 8
  selector:
    matchLabels:
      app: distance-conversion
  template:
    metadata:
      labels:
        app: distance-conversion
    spec:
      containers:
      - name: distance-conversion
        image: hbatistuzzo/distance-conversion:v2
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: distance-conversion
spec:
  selector:
      app: distance-conversion
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: NodePort